### ISSUE TITLE
doc: comparison against already existing libs.

### ISSUE THREAD

**Issue by mathpaquette** [morganstanley/needle#4]
how does that compare to existing lib doing that already? just to name few...
https://github.com/microsoft/tsyringe
https://github.com/inversify/InversifyJS

**Comment by Davidhanson90** [comment]
You will now find a feature table for needle here.  https://github.com/morganstanley/needle#feature-support  

Associated PR here - [Adding feature table with support status](https://github.com/morganstanley/needle/pull/36)

Generally getting into direct comparison with other libraries is not considered healthy for OSS projects.  Happy for community to do their own comparisons however.

**Comment by mathpaquette** [comment]
Maybe to highlight the limitations you faced using the other DI containers would help.

**Comment by Davidhanson90** [comment]
* Lacking type safety
* Obscure API
* Inconsistent approach to different DI concepts (lacking unity across them)
* Magic strings
* Focus on explicit binding & registrations Vs inferred via imports
* Poor documentation
* Backwards compatibility with older versions of typescript. 
* Dependency weight. 


I'll consider maybe putting these in main docs but they are normally emotive and subjective
